# Generated by Django 6.0.3 on 2026-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('is_phishing', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('reasons', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
